# Generated by Django 4.1.3 on 2022-12-07 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=10, verbose_name='серия')),
                ('number', models.IntegerField(verbose_name='номер')),
                ('release_date', models.DateTimeField(verbose_name='дата выпуска')),
                ('end_date', models.DateTimeField(verbose_name='дата окончания')),
                ('status', models.CharField(choices=[('a', 'active'), ('n', 'inactive'), ('e', 'expired')], max_length=1, verbose_name='статус')),
            ],
            options={
                'ordering': ['status', 'release_date'],
                'unique_together': {('series', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('amount', models.FloatField(verbose_name='сумма')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='app_card.card', verbose_name='карта')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
