# Generated by Django 4.1.3 on 2022-12-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='end_date',
            field=models.DateTimeField(db_index=True, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('e', 'inactive'), ('n', 'expired')], default='n', max_length=1, verbose_name='статус'),
        ),
    ]
